### ISSUE TITLE
Expand video list with other Dutch local channels.

### ISSUE THREAD

**Issue by pvdl** [bosel/plugin.video.nederland24#11]
Unfortunately local TV channels are not in the list.
This plugin is based on streams from NPO. 
It would be great to expand the list with other Dutch local TV channels.

Examples are AT5 or Omroep Gelderland.
These streams are also using a ('handshake') token to get it working only in the browser.
http://www.at5.nl/live
http://www.omroepgelderland.nl/web/show/id=73962/langid=43

**Comment by hsl1** [comment]
Add if you can RTL's SBS6 and NPO's HD
