### ISSUE TITLE
Subtitles cannot be disabled with the latest addon version

### ISSUE THREAD

**Issue by Klojum** [bosel/plugin.video.nederland24#21]
Currently, subtitles are constantly displayed for at least Nederland 1, 2 and 3 streams. The subtitle on/off function is not having any effect, either via the 't' key or via the OSD option.

**Comment by bosel** [comment]
Subtitles can be changed in plugin settings only, as the subtitled stream is not the same as the regular stream. 
No way around this that I am aware of.
