### ISSUE TITLE
Seems NPO streams return a 410 as of today

### ISSUE THREAD

**Issue by sphaero** [bosel/plugin.video.nederland24#24]
from kodi.log:
```
18:57:55 T:2623534144  NOTICE: -->Python Interpreter Initialized<--
18:57:56 T:2623534144  NOTICE: plugin.video.nederland24:: Starting Addon
18:57:56 T:2623534144  NOTICE: plugin.video.nederland24:: NPO Radio 1 not set
18:57:56 T:2623534144  NOTICE: plugin.video.nederland24:: NPO Radio 2 not set
18:57:56 T:2623534144  NOTICE: plugin.video.nederland24:: NPO 3FM not set
18:57:56 T:2623534144  NOTICE: plugin.video.nederland24:: NPO Radio 4 not set
18:57:56 T:2623534144  NOTICE: plugin.video.nederland24:: NPO Radio 6 not set
18:57:56 T:2623534144  NOTICE: plugin.video.nederland24:: NPO FunX not set
18:57:59 T:2623534144  NOTICE: plugin.video.nederland24:: No additional channels set
18:58:02 T:2623534144  NOTICE: Thread LanguageInvoker start, auto delete: false
18:58:02 T:2623534144  NOTICE: -->Python Interpreter Initialized<--
18:58:03 T:2623534144  NOTICE: plugin.video.nederland24:: Starting Addon
18:58:03 T:2623534144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 410: Gone
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.nederland24/nederland24.py", line 246, in <module>
                                                playVideo(url)
                                              File "/home/pi/.kodi/addons/plugin.video.nederland24/nederland24.py", line 213, in playVideo
                                                URL = API_URL+BASE_URL+media+"&token=%s" % collect_token()
                                              File "/home/pi/.kodi/addons/plugin.video.nederland24/nederland24.py", line 146, in collect_token
                                                response = urllib2.urlopen(req)
                                              File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
                                                return _opener.open(url, data, timeout)
                                              File "/usr/lib/python2.7/urllib2.py", line 407, in open
                                                response = meth(req, response)
                                              File "/usr/lib/python2.7/urllib2.py", line 520, in http_response
                                                'http', request, response, code, msg, hdrs)
                                              File "/usr/lib/python2.7/urllib2.py", line 445, in error
                                                return self._call_chain(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 379, in _call_chain
                                                result = func(*args)
                                              File "/usr/lib/python2.7/urllib2.py", line 528, in http_error_default
                                                raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
                                            HTTPError: HTTP Error 410: Gone
                                            -->
```

**Comment by mrarends** [comment]
NPO have changed some URL's around. I have changed some code to make it work again. But it is my first time using GitHub so searching for a way to upload my change :)

**Comment by sciurius** [comment]
In case of emergency, cut/paste as comment here :)

**Comment by sciurius** [comment]
Thanks, unfortunately markup screwed it...
Can you attach the file to a comment?

**Comment by mrarends** [comment]
I just fixed the markup

**Comment by sciurius** [comment]
???
Please attach the file to a comment.

**Comment by mrarends** [comment]
Uploading gives: Something went really wrong, and we can’t process that file.  (just a .txt file).

Can you not see the code in my comment?

**Comment by sciurius** [comment]
I can see the code but it is screwed up since github interprets it as being markdown. The (python-essential) structure is lost.
Can you mail a copy to squirrel at xs4all.nl ?

**Comment by mrarends** [comment]
#25 Hope this works, otherwise I will mail :)

**Comment by sciurius** [comment]
Yes, this works! Thanks!

**Comment by sciurius** [comment]
Hmm. I still get errors:

`20:21:46.962 T:139658762406336   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://pedgewarea23a.video.kpnstreaming.nl:80/session/256c06e6-fdeb-11e6-8fdd-9cb65498b840/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
`

**Comment by mrarends** [comment]
mmm strange. Here is my log
```
19:06:22.614 T:139855112054528   DEBUG: plugin.video.nederland24:: token: 2luvdllqi5pdthaq0kcb3tvm86
19:06:22.614 T:139855112054528   DEBUG: plugin.video.nederland24:: URL and token http://ida.omroep.nl/app.php/LI_NL1_4188102?adaptive=yes&token=2luvdllqi5pdthaq0kcb3tvm86
19:06:22.958 T:139855112054528   DEBUG: plugin.video.nederland24:: intermediate URL http://livestreams.omroep.nl/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8?hash=54423fa8709cc5c854a4a0e08ce1693a&type=jsonp&protection=url
19:06:23.013 T:139855112054528   DEBUG: plugin.video.nederland24:: Videopage setSource("http:\/\/l2cmaf21d09c910058b5bbc4000000.841e4293b325e484.smoote2i.npostreaming.nl\/d\/live\/npo\/tvlive\/npo1\/npo1.isml\/npo1.m3u8")
19:06:23.013 T:139855112054528   DEBUG: plugin.video.nederland24:: final URL http://l2cmaf21d09c910058b5bbc4000000.841e4293b325e484.smoote2i.npostreaming.nl/d/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
19:06:23.063 T:139855112054528    INFO: CPythonInvoker(103, /home/mark/.kodi/addons/plugin.video.nederland24/nederland24.py): script successfully run
19:06:23.074 T:139856583833344   DEBUG: Thread scriptobs 139856583833344 terminating
19:06:23.074 T:139858469636096    INFO: easy_acquire - Created session to http://l2cmaf21d09c910058b5bbc4000000.841e4293b325e484.smoote2i.npostreaming.nl
19:06:23.095 T:139855112054528    INFO: Python script stopped
19:06:23.095 T:139855112054528   DEBUG: Thread LanguageInvoker 139855112054528 terminating
19:06:23.133 T:139858469636096   DEBUG: CCurlFile::GetMimeType - http://l2cmaf21d09c910058b5bbc4000000.841e4293b325e484.smoote2i.npostreaming.nl/d/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8 -> application/vnd.apple.mpegurl
19:06:23.136 T:139858469636096   DEBUG: Loading settings for http://l2cmaf21d09c910058b5bbc4000000.841e4293b325e484.smoote2i.npostreaming.nl/d/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
19:06:23.137 T:139858469636096   DEBUG: CPlayerCoreFactory::GetPlayers(http://l2cmaf21d09c910058b5bbc4000000.841e4293b325e484.smoote2i.npostreaming.nl/d/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8)
```

**Comment by sciurius** [comment]
`20:36:46.423 T:139657622836992   DEBUG: plugin.video.nederland24:: Starting Addon
20:36:46.460 T:139657622836992   DEBUG: plugin.video.nederland24:: token: 1j84n7oflv37bqat15t3dn7ii6
20:36:46.460 T:139657622836992   DEBUG: plugin.video.nederland24:: URL and token http://ida.omroep.nl/app.php/LI_NL1_4188102?adaptive=yes&token=1j84n7oflv37bqat15t3dn7ii6
20:36:46.602 T:139657622836992   DEBUG: plugin.video.nederland24:: intermediate URL http://livestreams.omroep.nl/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8?hash=bce1a63716137043d19a0e5f7293cfa7&type=jsonp&protection=url
20:36:46.674 T:139657622836992   DEBUG: plugin.video.nederland24:: Videopage setSource("http:\/\/pedgewarea27b.video.kpnstreaming.nl:80\/session\/3dc29d02-fded-11e6-ad95-9cb65498b840\/fqimjj\/b2b\/live\/npo\/live\/npo\/tvlive\/npo1\/npo1.isml\/npo1.m3u8?token=2db03f568c11087f197167ae906aa2fd_1488397006_1488397006")
20:36:46.674 T:139657622836992   DEBUG: plugin.video.nederland24:: final URL http://pedgewarea27b.video.kpnstreaming.nl:80/session/3dc29d02-fded-11e6-ad95-9cb65498b840/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
20:36:46.720 T:139657622836992    INFO: CPythonInvoker(10, /home/jv/.kodi/addons/plugin.video.nederland24/nederland24.py): script successfully run
20:36:46.738 T:139657639622400   DEBUG: Thread scriptobs 139657639622400 terminating
20:36:46.739 T:139658762406336    INFO: easy_aquire - Created session to http://pedgewarea27b.video.kpnstreaming.nl
20:36:46.741 T:139657622836992    INFO: Python script stopped
20:36:46.741 T:139657622836992   DEBUG: Thread LanguageInvoker 139657622836992 terminating
20:36:46.801 T:139658762406336   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://pedgewarea27b.video.kpnstreaming.nl:80/session/3dc29d02-fded-11e6-ad95-9cb65498b840/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
20:36:46.801 T:139658762406336   DEBUG: CCurlFile::GetMimeType - http://pedgewarea27b.video.kpnstreaming.nl:80/session/3dc29d02-fded-11e6-ad95-9cb65498b840/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8 -> failed
`

**Comment by mrarends** [comment]
Is NPO working normally in your browser? I'm not customer of KPN so I'm not redirected to kpnstreaming.nl.

**Comment by marcknijn** [comment]
hi mrarends, I think I have the same issue as sciurius. I'm on a Telfort connection, but NPO works fine in my browser. Any idea's? 

21:25:53 T:804401152    INFO: CPythonInvoker(4, /var/mobile/Library/Preferences/Kodi/addons/plugin.video.nederland24-a2ab43c5b821800fad73e3577087a9bfbfa3bd15/nederland24.py): script successfully run
21:25:53 T:804401152    INFO: Python script stopped
21:25:53 T:804401152   DEBUG: Thread LanguageInvoker 0 terminating
21:25:53 T:145780736   DEBUG: DoWork - took 2945 ms to load special://masterprofile/Thumbnails/7/7c60ff7c.png
21:25:53 T:39915520   DEBUG: WaitOnScriptResult- plugin returned successfully
21:25:53 T:39915520    INFO: easy_aquire - Created session to http://pedgewarer29b.video.kpnstreaming.nl
21:25:53 T:39915520   ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22) for http://pedgewarer29b.video.kpnstreaming.nl:80/session/1a20153a-fdf4-11e6-9856-9cb65498e820/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
21:25:53 T:39915520   DEBUG: CCurlFile::GetMimeType - http://pedgewarer29b.video.kpnstreaming.nl:80/session/1a20153a-fdf4-11e6-9856-9cb65498e820/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8 -> failed
21:25:53 T:39915520   DEBUG: Loading settings for http://pedgewarer29b.video.kpnstreaming.nl:80/session/1a20153a-fdf4-11e6-9856-9cb65498e820/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
21:25:53 T:39915520   DEBUG: CPlayerCoreFactory::GetPlayers(http://pedgewarer29b.video.kpnstreaming.nl:80/session/1a20153a-fdf4-11e6-9856-9cb65498e820/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8)
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: system rules
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: system rules
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtv
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: hdhomerun/myth/mms/udp
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: lastfm/shout
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtmp
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: rtsp
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: streams
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: matches rule: streams
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: aacp/sdp
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: mp2
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvd
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: dvdimage
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: sdp/asf
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: nsv
21:25:53 T:39915520   DEBUG: CPlayerSelectionRule::GetPlayers: considering rule: radio
21:25:53 T:39915520   DEBUG: CPlayerCoreFactory::GetPlayers: matched 0 rules with players
21:25:53 T:39915520   DEBUG: CPlayerCoreFactory::GetPlayers: adding videodefaultplayer (1)
21:25:53 T:39915520   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=0
21:25:53 T:39915520   DEBUG: CPlayerCoreFactory::GetPlayers: for video=1, audio=1
21:25:53 T:39915520   DEBUG: CPlayerCoreFactory::GetPlayers: adding player: DVDPlayer (1)
21:25:53 T:39915520   DEBUG: CPlayerCoreFactory::GetPlayers: added 1 players
21:25:53 T:39915520  NOTICE: DVDPlayer: Opening: http://pedgewarer29b.video.kpnstreaming.nl:80/session/1a20153a-fdf4-11e6-9856-9cb65498e820/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
21:25:53 T:39915520 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:25:53 T:39915520   DEBUG: CRenderManager::UpdateDisplayLatency - Latency set to 0 msec
21:25:53 T:39915520   DEBUG: LinuxRendererGL: Cleaning up GL resources
21:25:53 T:804401152  NOTICE: Thread DVDPlayer start, auto delete: false
21:25:53 T:804401152  NOTICE: Creating InputStream
21:25:53 T:804401152   DEBUG: CFileCache::Open - opening <session/1a20153a-fdf4-11e6-9856-9cb65498e820/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8> using cache
21:25:53 T:804401152   DEBUG: CurlFile::Open(0x20e1bdf0) http://pedgewarer29b.video.kpnstreaming.nl:80/session/1a20153a-fdf4-11e6-9856-9cb65498e820/fqimjj/b2b/live/npo/live/npo/tvlive/npo1/npo1.isml/npo1.m3u8
21:25:53 T:804401152   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403

**Comment by mrarends** [comment]
The changes I've made seems to work correctly. The addon is first retrieving a token and then it retrieves the url of the m3u8 playlist. But the download of this file is not successful. 

Since Telfort is a doughter company of KPN it is also using kpnstreaming. Maybe for KPN we have to do something special?

Can you record a HAR file from viewing NPO in a browser?:
https://toolbox.googleapps.com/apps/har_analyzer/
and post it?

I have also just fixed the 'Uitzending gemist': https://github.com/Opvolger/plugin.video.uzg/pull/5 Is this also not working?

**Comment by sciurius** [comment]
I'm connected via XS4All. HAR at http://www.squirrel.nl/pub/xfer/uploads/3CeE_MxxphWoyIdUhGsq8wcw.har.gz

**Comment by rwielinga** [comment]
Thanks for your efforts guys, i also have this issue. Watching this topic for a resolution.

**Comment by juiced** [comment]
I temporarily "fixed" it by creating a VPN connection on the Kodi box to circumvent this "kpnstreaming redirect" thing. :-P

**Comment by mrarends** [comment]
Ok thanks for the extra information. It seems the kpnstreaming is working a bit different. I will study the HAR file to find a difference.

**Comment by marcknijn** [comment]
Thanks mrarends!

**Comment by mrarends** [comment]
In #25 I have committed a new version which hopefully also works with KPN.

**Comment by bosel** [comment]
Thank guys. Add-on should update fairly soon through Kodi. If you cannot wait, please download from here and place in your addon folder.
