### ISSUE TITLE
Subtitle and Event IDs

### ISSUE THREAD

**Issue by kyl416** [bosel/plugin.video.nederland24#26]
Here's the codes for the subtitle/TTT and Event/mcr streams so you can reactivate them:

LI_NL1_824154 - NPO 1 TTT
LI_NL2_824153 - NPO 2 TTT
LI_NL3_824151 - NPO 3 TTT

LI_NEDERLAND1_221709 - MCR1
LI_NEDERLAND2_221711 - MCR2
LI_NEDERLAND3_221713 - MCR3

**Comment by bosel** [comment]
Cheers!
