### ISSUE TITLE
Update knop niet bruikbaar

### ISSUE THREAD

**Issue by carsten888** [bosel/plugin.video.nederland24#31]
Ik heb versie 4.5.1. Deze doet het al een tijdje niet meer. Maar kan niet updaten naar de laatste versie want update knop blijft grijs (system > adons > videoadons > ned 24 onder knop 'configure').

Ook als ik in het repository kijk staat daar de oude versie.
system > adons > install from repository > video adons > kodi adon repository. staat nog 4.5.1 terwijl 4.5.6 al uit is. Wordt dat niet geupdate? Moet ik die uit een andere repository halen? Zo ja, welke is betrouwbaar?

Blijkt dat het met mij kodi versie te maken had. I was nog op kodi 15.2. Update naar 17.1 zorgde dat alles weer naar behoren werkt.

**Comment by bosel** [comment]
inderdaad
